# Generated by Django 5.0 on 2024-01-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='error_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(max_length=30)),
                ('module', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('applies_to', models.TextField()),
                ('symptoms', models.TextField()),
                ('cause', models.TextField()),
                ('solution', models.TextField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
