# Generated by Django 5.0 on 2024-01-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l1_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error_code',
            name='applies_to',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='error_code',
            name='cause',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='error_code',
            name='last_update',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='error_code',
            name='solution',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='error_code',
            name='symptoms',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='error_code',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
