# Generated by Django 5.0 on 2024-01-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l1_support', '0003_error_code_check_list_error_code_place_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error_code',
            name='check_list',
        ),
        migrations.RemoveField(
            model_name='error_code',
            name='place_holder',
        ),
    ]
